### ISSUE TITLE
Add “Sign in” button to Live demo tool bar

### ISSUE THREAD

**Issue by 7R41N33** [UffizziCloud/uffizzi_app#107]
Open modal and let the user signs in to an existing account

![image](https://user-images.githubusercontent.com/10543986/167247248-5969e59a-c22d-4f97-97b5-86884a2e5a9c.png)

![image](https://user-images.githubusercontent.com/10543986/167247278-0774c9e3-5f47-47a0-a089-0b06362a26ab.png)

**Comment by gadkins** [comment]
Closing this issue as it is no longer relevant
