### ISSUE TITLE
Support for the docker-compose `command` option

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_app#131]
Add parsing and handling of the `command` option as described in the docker-compose documentation.
https://docs.docker.com/compose/compose-file/#command

Kubernetes docs:
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/

**Comment by axisofentropy** [comment]
I feel like this already works? Maybe I'm mistaken and I haven't actually tested it.
