### ISSUE TITLE
Create a GitLab CI job for Uffizzi create, update, and delete env

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/uffizzi_app#184]
Similar to the GitHub Actions reusable workflow, we should author a job for GitLab CI that creates, updates, and delete preview environments, as well as, posts the preview URL as a comment to the merge request.

We probably should create a new directory in this repo for this job and similar jobs/actions for other providers (e.g. `gitlab/`, `circleci/`, etc.)

**Comment by moklidia** [comment]
The Gitlab project: https://gitlab.com/uffizzi/preview-action

Need to add the vote app to Gitlab as well.

**Comment by gadkins** [comment]
Since we cannot easily post the environment URL to the GitLab merge request issue, we should add a Slack job that take the URL and sends it to a channel in Slack. Look for existing Slack jobs for GitLab CI.
