### ISSUE TITLE
Organizational accounts should be changed to personal

### ISSUE THREAD

**Issue by antlu** [UffizziCloud/uffizzi_app#246]
Relates to https://github.com/UffizziCloud/uffizzi_platform/issues/107.

**Comment by antlu** [comment]
For testing refer to the comments in the related task for the platform.
https://github.com/UffizziCloud/uffizzi_platform/issues/107#issuecomment-1247967772

**Comment by fedorov-dualboot** [comment]
tested as part of the [107](https://github.com/UffizziCloud/uffizzi_platform/issues/107) task
