### ISSUE TITLE
Do not ask docker-hub credentials for public and official images

### ISSUE THREAD

**Issue by moklidia** [UffizziCloud/uffizzi_app#248]
Let users add and use official and public docker-hub images without connecting docker-hub integration.

**Comment by moklidia** [comment]
Cases:
1. Credential does not exist and the image is public
2. Credential does not exist and the image is private
3. Credential does not exist, and the public image does not exist
4. Correct credential exists, but the private image does not exist
5. Credential exists, but the private image is from a different namespace (Credential has username `limoha` but the image is from `uffizzitest` namespace)

**Comment by NealArw** [comment]
- [ ] Credential does not exist and the image is public
- [ ] Credential does not exist and the image is private
- [ ] Credential does not exist, and the public image does not exist
- [ ] Correct credential exists, but the private image does not exist
- [ ] Credential exists, but the private image is from a different namespace (Credential has username limoha but the image is from uffizzitest namespace)

**Comment by NealArw** [comment]
TESTING - Platform + CLI

- [ ] Credential does not exist and the image is public
- [ ] Credential does not exist and the image is official
- [ ] Credential does not exist and the image is private
- [ ] Credential does not exist, and the public image does not exist
- [ ] Correct credential exists, but the private image does not exist
- [ ] Correct credential exists, and the private image exists
- [ ] Credential exists, but the private image is from a different namespace (Credential has username limoha but the image is from uffizzitest namespace)

**Comment by NealArw** [comment]
**TESTED - OK**

**Comment by NealArw** [comment]
TESTING - APP + CLI

- [ ]  Credential does not exist and the image is public
- [ ]  Credential does not exist and the image is official
- [ ]  Credential does not exist and the image is private
- [ ]  Credential does not exist, and the public image does not exist
- [ ]  Correct credential exists, but the private image does not exist
- [ ]  Correct credential exists, and the private image exists
- [ ]  Credential exists, but the private image is from a different namespace (Credential has username limoha but the image is from uffizzitest namespace)

**Comment by NealArw** [comment]
TESTING on prod - Platform + CLI

- [ ]  Credential does not exist and the image is public
- [ ]  Credential does not exist and the image is official
- [ ]  Credential does not exist and the image is private
- [ ]  Credential does not exist, and the public image does not exist
- [ ]  Correct credential exists, but the private image does not exist
- [ ]  Correct credential exists, and the private image exists
- [ ]  Credential exists, but the private image is from a different namespace (Credential has username limoha but the image is from uffizzitest namespace)

**Comment by NealArw** [comment]
TESTING on prod - APP + CLI

- [ ]  Credential does not exist and the image is public
- [ ]  Credential does not exist and the image is official
- [ ]  Credential does not exist and the image is private
- [ ]  Credential does not exist, and the public image does not exist
- [ ]  Correct credential exists, but the private image does not exist
- [ ]  Correct credential exists, and the private image exists
- [ ]  Credential exists, but the private image is from a different namespace (Credential has username limoha but the image is from uffizzitest namespace)
