### ISSUE TITLE
BUG: Can't add compose file

### ISSUE THREAD

**Issue by 7R41N33** [UffizziCloud/uffizzi_app#70]
1. Create compose file in GitHub
2. Go to compose page
3. Fill repo name and branch fields
4. Fill path to compose field
5. Click Validate and Save

Result: Error: has already been taken
There is not file with same path in the DB

![image](https://user-images.githubusercontent.com/10543986/164229219-e84743c3-0bf2-40a8-ad57-a0337f455c95.png)
![image](https://user-images.githubusercontent.com/10543986/164229259-0516a9ce-2d36-49b0-8533-3200e106f098.png)

Reproduced on QA-GKE for user with id=106

**Comment by zipofar** [comment]
I could not reproduce this case

**Comment by NealArw** [comment]
Does not reproduced.
