### ISSUE TITLE
uffizzi project create backend

### ISSUE THREAD

**Issue by 7R41N33** [UffizziCloud/uffizzi_app#83]
We need to implement API for the `uffizzi project create` command
https://github.com/UffizziCloud/uffizzi_cli/issues/77

**Comment by moklidia** [comment]
`[POST] /api/cli/v1/projects`

**Comment by NealArw** [comment]
1. There is no information about route in the /api-docs

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/165893053-20dce969-a627-4da7-92fd-0b2223e42de8.png">

**Comment by NealArw** [comment]
2. Needs to add information about  parameters for request in /api-docs

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/165926002-e122c623-a46f-47e3-876d-eca7010acbc6.png">

**Comment by moklidia** [comment]
Swagger documentation updated

**Comment by AnnaPochepina** [comment]
verified in production
