### ISSUE TITLE
uffizzi project delete backend

### ISSUE THREAD

**Issue by 7R41N33** [UffizziCloud/uffizzi_app#84]
We need to implement API for the `uffizzi project delete` command
https://github.com/UffizziCloud/uffizzi_cli/issues/78

**Comment by moklidia** [comment]
`[DELETE] /api/cli/v1/projects/{slug}`

**Comment by NealArw** [comment]
1. There is no information about route in the /api-docs

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/89470900/165893053-20dce969-a627-4da7-92fd-0b2223e42de8.png">

**Comment by NealArw** [comment]
**TESTED - OK**
